spring.application.name=wtc

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://ruicesarcastilho37_db_user:31077399Le@mongo-pratica.nrt18my.mongodb.net/wtc_db?retryWrites=true&w=majority

# JWT
jwt.secret=wtc_projeto_fiap_chave_secreta_2026
jwt.expiration=86400000

# Servidor
server.port=8080

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
